USE CATALOGO
GO

SELECT * FROM GENERO;
GO

SELECT * FROM FILME;
GO

SELECT idFilme, tituloFilme, nomeGenero FROM FILME
LEFT JOIN GENERO
ON FILME.idGenero = GENERO.idGenero;

-- LISTAR SOMENTE OS FILMES QUE POSSUEM GÊNERO, TRAZENDO TAMBÉM
-- TODOS OS GÊNEROS QUE NÃO REPRESENTEM UM FILME
-- RIGHT JOIN
SELECT idFilme, tituloFilme, nomeGenero FROM FILME
RIGHT JOIN GENERO
ON FILME.idGenero = GENERO.idGenero;

-- LISTAR SOMENTE OS FILMES QUE POSSUAM UM GÊNERO DEFINIDO
-- GÊNEROS QUE NÃO CORRESPONDAM A ALGUM FILME NÃO DEVEM SER MOSTRADOS
-- INNER JOIN
SELECT idFilme, tituloFilme, nomeGenero FROM FILME
INNER JOIN GENERO
ON FILME.idGenero = GENERO.idGenero;

-- LISTAR TODOS OS FILMES E TODOS OS GÊNEROS,
-- MESMO QUE NÃO HAJA CORRESPONDÊNCIA ENTRE ELES
-- FULL OUTER JOIN
SELECT idFilme, tituloFilme, nomeGenero FROM FILME
FULL OUTER JOIN GENERO
ON FILME.idGenero = GENERO.idGenero;