CREATE DATABASE PETSHOP;
GO

USE PETSHOP;
GO

CREATE TABLE CLINICA (
 idClinica TINYINT PRIMARY KEY  IDENTITY(1,1),
 nomeClinica VARCHAR(20) NOT NULL,
 enderecoClinica VARCHAR(50) NOT NULL,
);
GO 

CREATE TABLE DONO	 (
 idDono SMALLINT PRIMARY KEY  IDENTITY(1,1),
 nomeDono VARCHAR(20) NOT NULL,
);
GO 

CREATE TABLE TIPOPET (
 idTipopet SMALLINT PRIMARY KEY  IDENTITY(1,1),
 Tipo VARCHAR(50) NOT NULL,
);
GO 

CREATE TABLE VETERINARIO(
idVeterinario SMALLINT PRIMARY KEY  IDENTITY(1,1),
idClinica TINYINT FOREIGN KEY REFERENCES CLINICA(idClinica),
Nomevet CHAR(15) NOT NULL 
);
GO

CREATE TABLE RACAS(
idRacas SMALLINT PRIMARY KEY  IDENTITY(1,1),
idTipopet SMALLINT FOREIGN KEY REFERENCES TIPOPET(idTipopet),
Qualraca CHAR(15) NOT NULL 
);
GO

CREATE TABLE PET(
idPet SMALLINT PRIMARY KEY  IDENTITY(1,1),
idRacas SMALLINT FOREIGN KEY REFERENCES RACAS(idRacas),
idDono SMALLINT FOREIGN KEY REFERENCES DONO(idDono),
NomePet CHAR(10) NOT NULL 
);
GO

CREATE TABLE ATENDIMENTO(
idAtendimento SMALLINT PRIMARY KEY  IDENTITY(1,1),
idVeterinario SMALLINT FOREIGN KEY REFERENCES VETERINARIO(idVeterinario),
idPet SMALLINT FOREIGN KEY REFERENCES PET(idPet),
Horario_Atendimento CHAR(20) NOT NULL
);
GO



